apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary
  labels:
    app: nginx
    branch: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      branch: green
  template:
    metadata:
      labels:
        app: nginx
        track: canary
        Version: 1.9.1
        branch: green
    spec:
      containers:
      - name: nginx
        image: gcr.io/w255-instructor/nginx:green
        ports:
        - containerPort: 80
