apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: w255
spec:
  type: LoadBalancer
  selector:
    app: nginx
  #sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 80
